agentTester:
  enabled: AGENT_TESTER_ENABLED
  useAuth: AGENT_TESTER_USE_AUTH
  openAi:
    apiKey: AGENT_TESTER_OPENAI_API_KEY
    baseURL: AGENT_TESTER_OPENAI_BASE_URL

cache:
  ttlSeconds: CACHE_TTL_SECONDS
  maxItems: CACHE_MAX_ITEMS
  checkPeriod: CACHE_CHECK_PERIOD

db:
  postgres:
    dbs:
      main:
        database: DB_NAME
        host: DB_HOST
        port: DB_PORT
        user: DB_USER
        password: DB_PASSWORD

logger:
  level: LOGGER_LEVEL
  useFileLogger: LOGGER_USE_FILE_LOGGER
  dir: LOGGER_DIR

mcp:
  transportType: MCP_TRANSPORT_TYPE
  toolAnswerAs: MCP_TOOL_ANSWER_AS
  rateLimit:
    maxRequests: MCP_RATE_LIMIT_MAX_REQUESTS
    windowMs: MCP_RATE_LIMIT_WINDOW_MS

uiColor:
  primary: UI_COLOR_PRIMARY

webServer:
  host: WS_HOST
  port: WS_PORT
  auth:
    enabled: WS_AUTH_ENABLED
    permanentServerTokens: WS_SERVER_TOKENS # comma separated list
    jwtToken:
      encryptKey: WS_TOKEN_ENCRYPT_KEY
      checkMCPName: WS_CHECK_MC_NAME
    basic:
      username: WS_AUTH_BASIC_USERNAME
      password: WS_AUTH_BASIC_PASSWORD
  adminAuth:
    enabled: WS_ADMIN_AUTH_ENABLED
    type: WS_ADMIN_AUTH_TYPE  # permanentServerTokens | basic | jwtToken | ntlm
